// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EM
Rcpp::NumericVector EM(const arma::mat& A, int maxiter, double rtol);
RcppExport SEXP _ebTobit_EM(SEXP ASEXP, SEXP maxiterSEXP, SEXP rtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type rtol(rtolSEXP);
    rcpp_result_gen = Rcpp::wrap(EM(A, maxiter, rtol));
    return rcpp_result_gen;
END_RCPP
}
// lik_GaussianPIC
double lik_GaussianPIC(Rcpp::NumericVector L, Rcpp::NumericVector R, Rcpp::NumericVector gr, Rcpp::NumericVector s1);
RcppExport SEXP _ebTobit_lik_GaussianPIC(SEXP LSEXP, SEXP RSEXP, SEXP grSEXP, SEXP s1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gr(grSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s1(s1SEXP);
    rcpp_result_gen = Rcpp::wrap(lik_GaussianPIC(L, R, gr, s1));
    return rcpp_result_gen;
END_RCPP
}
// likMat
Rcpp::NumericMatrix likMat(Rcpp::NumericMatrix L, Rcpp::NumericMatrix R, Rcpp::NumericMatrix gr, Rcpp::NumericMatrix s1);
RcppExport SEXP _ebTobit_likMat(SEXP LSEXP, SEXP RSEXP, SEXP grSEXP, SEXP s1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type L(LSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gr(grSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type s1(s1SEXP);
    rcpp_result_gen = Rcpp::wrap(likMat(L, R, gr, s1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ebTobit_EM", (DL_FUNC) &_ebTobit_EM, 3},
    {"_ebTobit_lik_GaussianPIC", (DL_FUNC) &_ebTobit_lik_GaussianPIC, 4},
    {"_ebTobit_likMat", (DL_FUNC) &_ebTobit_likMat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ebTobit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
