# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Nonparametric Maximum Likelihood via Expectation Maximization
#'
#' Compute the nonparametric maximum likelihood estimate given a likelihood
#' matrix. The matrix A is structured so that A_\{ij\} = f(X_i | theta_j) for
#' some grid of potential parameter values theta_1, ..., theta_p and
#' observations X_1, ..., X_n. The parameters, theta_j, can be multidimensional
#' because all that is required is the likelihood. Convergence is achieved when
#' the relative improvements of the log-likelihood is below the provided
#' tolerance level.
#'
#' @param A numeric matrix likelihoods
#' @param maxiter early stopping condition
#' @param tol convergence tolerance
#' @return the estimated prior distribution (a vector of masses corresponding
#' to the columns of A)
#'
#' @examples
#' set.seed(1)
#' t = sample.int(5, size = 1000, replace = TRUE)
#' x = t + stats::rnorm(1000)
#' gr = seq(from = min(x), to = max(x), length.out = 500)
#' A = stats::dnorm(outer(x, gr, "-"))
#' EM(A)
#'
#' \dontrun{
#' all.equal(
#'     REBayes::KWPrimal(A = A, d = rep(1, 500), w = rep(1/1000, 1000))$f,
#'     drop(EM(A, maxiter = 1e+9, tol = 1e-16)) # EM alg converges slowly
#' )
#' }
#'
#' @useDynLib EBGaME
#' @importFrom Rcpp evalCpp
#' @export
EM <- function(A, maxiter = 1000L, tol = 1e-6) {
    .Call('_EBGaME_EM', PACKAGE = 'EBGaME', A, maxiter, tol)
}

